"""The scan report handed to the USER (task 9).

Two different people read two different documents about the same scan, and
conflating them is what made the first attempt at this task miss its
requirement (2026-08-10):

- `hawkeye scout`'s output, including the check sheet in
  `hawkeye/reports/monitor_ja.py`, is read by the orchestrating session. It is
  a working surface: dense, per-vendor, full of retrieval detail.
- THIS report is read by the user, at one point in `/hawkeye-run` — after the
  guidance step, before any case is opened. It answers four questions and
  stops: which names are about to be argued over, what earned them their
  score, what else was handed to the tribunal about them, and what happened
  to everything else the scan looked at.

Built from the ledger rather than from the in-memory scan, so it can be
produced (and reproduced) at the moment the user is actually asked to decide,
rather than only in the seconds after the scan finishes.

Generated by code and not by an instruction in the skill file: a step a
prompt requests is a step that gets skipped, and the user would then be
deciding on whatever the session chose to summarise that day.
"""
from __future__ import annotations

import csv
import io
from typing import Iterable, Optional

from hawkeye.contracts.models import (
    AnalystTrend,
    GateReport,
    InsiderActivity,
    NewsItem,
    ScreenedCandidate,
    ScreenedCandidateStage,
)
from hawkeye.reports.quality_ja import _flag_ja

# The seven entry-gate conditions, in the words of what they actually check.
# The stored name is an English identifier; a user asked to accept a rejection
# cannot check one they cannot read.
_GATE_JA = {
    "min_price": "株価",
    "min_market_cap": "時価総額",
    "min_avg_dollar_volume": "売買代金(20日平均)",
    "catalyst_freshness_days": "決算からの経過日数",
    "event_gap_not_extreme": "決算当日の値動きの大きさ",
    "volatility_sane": "値動きの荒さ(14日ATR)",
    "earnings_proximity": "次の決算までの日数",
}
_SOURCE_JA = {"whispers": "決算専門サイト", "calendar": "決算カレンダー"}
# How far the funnel carried a name. Same vocabulary as the check sheet, so a
# reader holding both documents is not learning two sets of words.
_STAGE_JA = {
    ScreenedCandidateStage.ACTUAL_PENDING: "決算の数値が未着(保留)",
    ScreenedCandidateStage.ACTUAL_TIMEOUT: "数値が届かないまま打ち切り",
    ScreenedCandidateStage.ENRICHMENT_CAP: "順位が下位で詳細を取得せず",
    ScreenedCandidateStage.GATE_REJECT: "入口ゲートで落選",
    ScreenedCandidateStage.RANKING_CUTOFF: "入口ゲート通過",
}
# The five things that can earn ranking points, in the words the user used
# when asking for the breakdown.
_BREAKDOWN_JA = (
    ("eps", "EPSサプライズ"),
    ("revenue", "売上サプライズ"),
    ("gap", "決算当日の値動き"),
    ("guidance", "会社のガイダンス"),
    ("whisper", "囁き予想の上回り"),
)

_CSV_COLUMNS: tuple[tuple[str, str], ...] = (
    ("ティッカー", "ticker"),
    ("発表日", "event_date"),
    ("順位", "rank"),
    ("到達段階", "stage"),
    ("数値の出所", "numbers_source"),
    ("EPSサプライズ率", "eps_surprise_pct"),
    ("売上サプライズ率", "revenue_surprise_pct"),
    ("点数", "score"),
    ("EPSで得た点", "eps"),
    ("売上で得た点", "revenue"),
    ("決算当日の値動きで得た点", "gap"),
    ("ガイダンスで得た点", "guidance"),
    ("囁き予想で得た点", "whisper"),
    ("株価", "price"),
    ("落選理由", "drop_reason"),
    ("取得できなかった理由", "numbers_reason"),
)


def render_scan_report_ja(scan: dict, candidates: list[ScreenedCandidate],
                          top_n: int = 3) -> str:
    """One scan, as the user reads it before saying whether to proceed."""
    ranked, others = _split(candidates, top_n)
    lines = _header(scan, candidates)
    lines += _tribunal_section(scan, ranked, top_n)
    lines += _material_section(ranked)
    lines += _table_section(ranked + others)
    lines += _errors_section(candidates)
    return "\n".join(lines)


# --- header -----------------------------------------------------------------

def _header(scan: dict, candidates: list[ScreenedCandidate]) -> list[str]:
    params = scan.get("params") or {}
    start, end = params.get("window_start", "?"), params.get("window_end", "?")
    return [
        f"# 📄 走査レポート({start} 〜 {end})",
        "",
        f"走査番号 {scan.get('id', '?')} / 実行 {scan.get('ts', '?')} / "
        f"記録された銘柄 {len(candidates)}件",
        "",
        f"決算イベント {scan.get('scanned', 0)}件 → サプライズ選別 "
        f"{scan.get('screened', 0)}件 → 詳細取得 {scan.get('enriched', 0)}件 "
        f"→ 入口ゲート通過 {scan.get('gate_passed', 0)}件",
        "",
        "この回の走査が**何を見て、何を審理に送り、他を何故落としたか**の報告です。"
        "審理(強気役・反論役・裁定役による対審)はまだ始まっていません。",
        "",
    ]


# --- ① the names going to the tribunal --------------------------------------

def _tribunal_section(scan: dict, ranked: list[ScreenedCandidate],
                      top_n: int) -> list[str]:
    lines = [f"## ① 審理に送る{top_n}銘柄", ""]
    lines += _missing_ranked_note(scan, ranked, top_n)
    if not ranked:
        if not scan.get("gate_passed"):
            lines += ["審理に送れる銘柄は **0件** でした"
                      "(入口ゲートを通過した銘柄がありません)。", ""]
        return lines
    for c in ranked:
        lines.append(f"### {c.rank or '-'}位 {c.ticker} — 点数 {c.score:g}")
        lines.append("")
        lines += _breakdown_lines(c)
        lines.append("")
        lines += _gate_lines(c.gate_report)
        lines.append("")
    return lines


def _missing_ranked_note(scan: dict, ranked: list[ScreenedCandidate],
                         top_n: int) -> list[str]:
    """Names the scan ranked but this report cannot describe.

    The ledger's drop table records what a run did NOT forward. A run started
    with `--open-cases N` forwards its top N in the same breath, so those rows
    are never written — and this report, built from that table, would print
    the fourth-placed name as if it were the first. The report has to say the
    detail is missing; silently showing a shorter list is the failure mode
    this whole document exists to prevent.
    """
    gate_passed = scan.get("gate_passed") or 0
    expected = min(top_n, gate_passed)
    if len(ranked) >= expected:
        return []
    named = [t for t in (scan.get("tickers") or [])[:expected]
             if t not in {c.ticker for c in ranked}]
    return [f"⚠️ **上位 {expected}銘柄のうち {expected - len(ranked)}件"
            f"({'、'.join(named) or '銘柄名も不明'})の詳細がここにありません。**"
            "この走査は候補を審理に直接送る指定"
            "(`--open-cases`)付きで実行されたため、送られた銘柄は"
            "「落選記録」に残らず、このレポートの材料が存在しません。"
            "`/hawkeye-run` の手順どおり `--open-cases` を付けずに走査すれば"
            "全件そろいます。",
            ""]


def _breakdown_lines(c: ScreenedCandidate) -> list[str]:
    """What earned the score, or an honest statement that nothing recorded it.

    Five zeros would read as "nothing earned any points", which is a claim
    about the company. "Not recorded" is a claim about us, and it is the true
    one for any row written before this field existed.
    """
    if c.score_breakdown is None:
        return ["**点数の内訳は記録されていません**"
                "(この行は内訳を記録するようになる前の走査のものです)。"]
        # 内訳が無くても点数そのものは上の見出しに出ている。
    b = c.score_breakdown
    parts = "  ".join(f"{label} {getattr(b, attr):+g}"
                      for attr, label in _BREAKDOWN_JA)
    lines = [f"点数の内訳: {parts}"]
    # The guidance term is zero on every session-mode scan, because the
    # company's outlook is read by an agent AFTER the scan while this score
    # was computed during it. Printing "会社のガイダンス +0" with no
    # explanation says the company guided nothing, which is a claim about the
    # company; the truth is a claim about the order our own steps run in.
    if b.guidance == 0:
        lines += ["",
                  "⚠️ 「会社のガイダンス」が0点なのは、この点数が**走査した時点**"
                  "のものだからです。会社の見通しはそのあとの工程でAIが読むため、"
                  "この欄には反映されていません(順位もこの点数で決まっています)。"]
    lines += ["",
              "(ニュース・インサイダー売買・アナリスト推奨は**点数には使って"
              "いません**。審理に渡す資料です)"]
    return lines


def _gate_lines(report: Optional[GateReport]) -> list[str]:
    if report is None:
        return ["入口ゲートの判定は記録されていません。"]
    lines = ["入口ゲート7条件:"]
    for g in report.results:
        if g.unverified:
            mark, tail = "⚠️", " — 判定に必要な数値が取れませんでした"
        elif g.passed:
            mark, tail = "✅", ""
        else:
            mark = "❌" if g.hard else "⚠️"
            tail = " — 不合格" if g.hard else " — 注意(致命的ではない)"
        # The measured figure is printed even when the condition has no
        # numeric bar (`earnings_proximity` passes on any date far enough
        # out). Without this branch that line read as a bare ✅ with nothing
        # behind it — a condition the reader is told cleared, on evidence they
        # were not shown (found on the first live run).
        if g.value is not None and g.threshold is not None:
            value = f" (実測 {g.value:,.2f} / 基準 {g.threshold:,.2f})"
        elif g.value is not None:
            value = f" (実測 {g.value:,.2f})"
        else:
            value = ""
        lines.append(f"- {mark} {_GATE_JA.get(g.name, g.name)}{value}{tail}")
    return lines


# --- ② everything that was NOT the earnings figures -------------------------

def _material_section(ranked: list[ScreenedCandidate]) -> list[str]:
    lines = ["## ② 決算値以外に、審理へ渡す情報", "",
             "⚠️ **これらは点数には使っていません。** 点数はEPS・売上・"
             "会社のガイダンス・囁き予想・決算当日の値動きの5つだけで決まります。"
             "ここに挙げるのは、審理で強気役と反論役が材料として読むものです。",
             ""]
    if not ranked:
        lines += ["該当なし。", ""]
        return lines
    for c in ranked:
        lines.append(f"### {c.ticker}")
        lines += _news_lines(c.news)
        lines.append(_insider_line(c.insider_activity))
        lines.append(_analyst_line(c.analyst_trend))
        lines.append("")
    return lines


def _news_lines(news: list[NewsItem]) -> list[str]:
    if not news:
        return ["- ニュース: 取得できたものはありません"]
    out = []
    for item in news:
        day = (item.published_at.date().isoformat()
               if item.published_at else "日付不明")
        source = f"({item.source})" if item.source else ""
        out.append(f"- ニュース {day}: 「{item.headline}」{source}")
    return out


def _insider_line(activity: Optional[InsiderActivity]) -> str:
    if activity is None:
        return "- インサイダー売買: 記録なし(取得できなかったか、届出が無い)"
    direction = "買い越し" if activity.net_shares > 0 else "売り越し"
    return (f"- インサイダー売買: 直近{activity.window_days}日で "
            f"{abs(activity.net_shares):,.0f}株の{direction}"
            f"(買った人 {activity.buyers}人 / 売った人 {activity.sellers}人)")


def _analyst_line(trend: Optional[AnalystTrend]) -> str:
    if trend is None:
        return "- アナリスト推奨: 記録なし"
    now = (f"強気買い {trend.strong_buy} / 買い {trend.buy} / "
           f"中立 {trend.hold} / 売り {trend.sell} / "
           f"強気売り {trend.strong_sell}")
    if trend.prior_period is None:
        return f"- アナリスト推奨({trend.period}時点): {now}"
    before = (f"強気買い {trend.prior_strong_buy} / 買い {trend.prior_buy} / "
              f"中立 {trend.prior_hold} / 売り {trend.prior_sell} / "
              f"強気売り {trend.prior_strong_sell}")
    return (f"- アナリスト推奨: {trend.prior_period}時点は {before} → "
            f"{trend.period}時点は {now}")


# --- ③ every name the scan recorded -----------------------------------------

def _looked_at_closely(c: ScreenedCandidate) -> bool:
    """Whether anything beyond the calendar's own figures happened to a name.

    True when the earnings feed was asked about it (it answered, or it
    declined by name), or when the walk reached it at all — enrichment, the
    entry gates, or a hold waiting for its numbers.

    Everything else cleared the surprise screen and then sat below the
    request budget, so its row would read: calendar figures, calendar source,
    and the same one-sentence reason as every other such row. On the first
    live run that was 121 of 171 rows, and it buried the fifty that record an
    actual retrieval decision — the same failure the check sheet hit on
    2026-08-10.
    """
    return (c.numbers_source == "whispers" or bool(c.numbers_reason)
            or c.gate_report is not None
            or c.stage in (ScreenedCandidateStage.GATE_REJECT,
                           ScreenedCandidateStage.ACTUAL_PENDING,
                           ScreenedCandidateStage.ACTUAL_TIMEOUT))


def _table_section(rows: list[ScreenedCandidate]) -> list[str]:
    shown = [c for c in rows if _looked_at_closely(c)]
    hidden = len(rows) - len(shown)
    lines = [f"## ③ 走査した銘柄({len(shown)}件)", ""]
    if not shown:
        lines += [f"表に出せる銘柄は **0件** です"
                  f"(この回に記録された銘柄は {len(rows)}件)。", ""]
        return lines
    lines += ["決算専門サイトに数字を問い合わせた銘柄と、入口ゲートまで進んだ"
              "銘柄の全件です。「落選理由」はどの段階で外れたかを示します。",
              "",
              "| ティッカー | 発表日 | 順位 | EPSサプライズ | 売上サプライズ "
              "| 数値の出所 | 点数 | 落選理由 |",
              "| --- | --- | --- | --- | --- | --- | --- | --- |"]
    for c in shown:
        lines.append(
            f"| {c.ticker} | {c.event_date} | {c.rank or '-'} "
            f"| {_pct(c.eps_surprise_pct)} | {_pct(c.revenue_surprise_pct)} "
            f"| {_SOURCE_JA.get(c.numbers_source, c.numbers_source)} "
            f"| {c.score:g} | {_drop_reason_ja(c)} |")
    lines.append("")
    if hidden:
        lines += [f"ほかに **{hidden}件** が、サプライズの足切りは通ったものの"
                  f"順位が下位で、決算専門サイトへの問い合わせにも詳細取得にも"
                  f"進みませんでした(上限は設定値 `scout_max_whispers` / "
                  f"`scout_max_enrich`)。数値は決算カレンダーのもの1種類しか"
                  f"無く、落選理由も全件同じなので表からは省いています — "
                  f"**CSVには全{len(rows)}件が入っています**。", ""]
    return lines


def _drop_reason_ja(c: ScreenedCandidate) -> str:
    """Why this name is not in the tribunal, in words that name the condition.

    The stored `reject_reason` is an English identifier written for a later
    machine review. Rebuilding the sentence from the gate report instead means
    the user reads WHICH condition refused the company, which is the only form
    of the answer they can disagree with.
    """
    if c.stage is ScreenedCandidateStage.GATE_REJECT:
        if c.gate_report is None:
            return "入口ゲートで落選(判定の記録なし)"
        failed = [_GATE_JA.get(g.name, g.name)
                  for g in c.gate_report.results
                  if g.hard and (not g.passed or g.unverified)]
        if failed:
            return "入口ゲート不合格: " + " / ".join(failed)
        return "入口ゲートで落選(致命的な不合格は記録されていません)"
    if c.stage is ScreenedCandidateStage.RANKING_CUTOFF:
        return (f"入口ゲート通過(順位 {c.rank}位)" if c.rank
                else _STAGE_JA[c.stage])
    return _STAGE_JA.get(c.stage, str(c.stage))


# --- ④ what could not be retrieved ------------------------------------------

def _errors_section(candidates: list[ScreenedCandidate]) -> list[str]:
    """Named failures, per ticker.

    Printed at zero as well: a section that vanishes when nothing failed reads
    as a check nobody ran, and this is the one place a silent data outage
    would otherwise be invisible to the user.
    """
    failures = [c for c in candidates if c.numbers_reason]
    conflicts = [c for c in candidates if c.conflicting_estimates]
    lines = [f"## ④ 取得できなかったもの({len(failures) + len(conflicts)}件)",
             ""]
    if not failures and not conflicts:
        lines += ["**0件** — この回はどの銘柄でも数値の取得に失敗していません。",
                  ""]
        return lines
    if failures:
        lines += ["決算専門サイトが数字を出せなかった銘柄です。"
                  "いずれも決算カレンダーの数字で順位を付けています。", ""]
    # Grouped by reason, not listed per ticker: the reason sentences are long,
    # and thirteen repetitions of three sentences hide which reason is the
    # common one. The grouping is what says "the site was down" rather than
    # "these thirteen companies are odd".
    by_reason: dict[str, list[str]] = {}
    for c in failures:
        by_reason.setdefault(c.numbers_reason, []).append(c.ticker)
    for reason, tickers in by_reason.items():
        lines.append(f"- {_flag_ja(reason)} — **{len(tickers)}件**: "
                     f"{'、'.join(tickers)}")
    for c in conflicts:
        lines.append(f"- **{c.ticker}**: 決算カレンダーが同じ決算に矛盾する行を"
                     f"返しました(最も保守的な読みを採用しています)")
    lines.append("")
    return lines


# --- the same rows, for a spreadsheet ---------------------------------------

def scan_report_csv(candidates: Iterable[ScreenedCandidate]) -> str:
    """One line per candidate, translated exactly as the screen translates it.

    The file and the screen are read by the same person, so a spreadsheet full
    of `gate_reject` and `whispers_server_error` is not a second surface — it
    is the same surface with the translation removed.
    """
    buffer = io.StringIO()
    writer = csv.writer(buffer, lineterminator="\n")
    writer.writerow([header for header, _ in _CSV_COLUMNS])
    for c in candidates:
        writer.writerow([_csv_cell(attr, c) for _, attr in _CSV_COLUMNS])
    return buffer.getvalue()


def _csv_cell(attr: str, c: ScreenedCandidate) -> str:
    if attr == "stage":
        return _STAGE_JA.get(c.stage, str(c.stage))
    if attr == "numbers_source":
        return _SOURCE_JA.get(c.numbers_source, c.numbers_source)
    if attr == "numbers_reason":
        return _flag_ja(c.numbers_reason) if c.numbers_reason else ""
    if attr == "drop_reason":
        return _drop_reason_ja(c)
    if attr in ("eps_surprise_pct", "revenue_surprise_pct"):
        value = getattr(c, attr)
        return "" if value is None else f"{round(value, 2):g}"
    if attr in ("eps", "revenue", "gap", "guidance", "whisper"):
        if c.score_breakdown is None:
            return ""
        return f"{getattr(c.score_breakdown, attr):g}"
    value = getattr(c, attr, None)
    return "" if value is None else str(value)


def _pct(value: Optional[float]) -> str:
    return "-" if value is None else f"{value:+.1f}%"


def _split(candidates: list[ScreenedCandidate], top_n: int
           ) -> tuple[list[ScreenedCandidate], list[ScreenedCandidate]]:
    """(the names going to the tribunal, everything else).

    Ranked names come first and in rank order; the rest keep the ledger's own
    order, which is the order the scan dropped them in.
    """
    ranked = sorted((c for c in candidates
                     if c.rank is not None and c.rank <= top_n),
                    key=lambda c: c.rank or 0)
    chosen = {c.id for c in ranked}
    return ranked, [c for c in candidates if c.id not in chosen]
