"""The scan report handed to the USER (task 9).

Two different people read two different documents about the same scan, and
conflating them is what made the first attempt at this task miss its
requirement (2026-08-10):

- `hawkeye scout`'s output, including the check sheet in
  `hawkeye/reports/monitor_ja.py`, is read by the orchestrating session. It is
  a working surface: dense, per-vendor, full of retrieval detail.
- THIS report is read by the user, at one point in `/hawkeye-run` — after the
  guidance step, before any case is opened. It answers four questions and
  stops: which names are about to be argued over, what earned them their
  score, what else was handed to the tribunal about them, and what happened
  to everything else the scan looked at.

Built from the ledger rather than from the in-memory scan, so it can be
produced (and reproduced) at the moment the user is actually asked to decide,
rather than only in the seconds after the scan finishes.

Generated by code and not by an instruction in the skill file: a step a
prompt requests is a step that gets skipped, and the user would then be
deciding on whatever the session chose to summarise that day.
"""
from __future__ import annotations

import csv
import io
from typing import Iterable, Optional

from hawkeye.contracts.models import (
    AnalystTrend,
    GateReport,
    GuidanceComparison,
    GuidanceState,
    InsiderActivity,
    NewsItem,
    ScreenedCandidate,
    ScreenedCandidateStage,
)
from hawkeye.reports.quality_ja import _flag_ja

# The seven entry-gate conditions, in the words of what they actually check.
# The stored name is an English identifier; a user asked to accept a rejection
# cannot check one they cannot read.
_GATE_JA = {
    "min_price": "株価",
    "min_market_cap": "時価総額",
    "min_avg_dollar_volume": "売買代金(20日平均)",
    "catalyst_freshness_days": "決算からの経過日数",
    "event_gap_not_extreme": "決算当日の値動きの大きさ",
    "volatility_sane": "値動きの荒さ(14日ATR)",
    "earnings_proximity": "次の決算までの日数",
}
# The vendor by name, not by description (T-014). The user knows these two as
# EW and Finnhub and reads the table by vendor; "決算専門サイト" made them
# translate back on every row. The prose sections keep the plain-Japanese
# description and introduce the abbreviation once, so a reader who has never
# heard of either still knows what they are.
_SOURCE_JA = {"whispers": "EW", "calendar": "Finnhub"}
# What the four-state guidance answer says in the table (T-014). The three
# ways of having no outlook are kept apart here for the same reason they are
# kept apart in the record: only the first is a fact about the company.
_GUIDANCE_STATE_JA = {
    GuidanceState.DISCLOSED: "開示あり",
    GuidanceState.NOT_PUBLISHED: "開示なし",
    GuidanceState.UNREADABLE: "読めず",
    GuidanceState.NOT_ATTEMPTED: "未取得",
    GuidanceState.UNKNOWN: "記録なし",
}
# How far the funnel carried a name. Same vocabulary as the check sheet, so a
# reader holding both documents is not learning two sets of words.
_STAGE_JA = {
    ScreenedCandidateStage.ACTUAL_PENDING: "決算の数値が未着(保留)",
    ScreenedCandidateStage.ACTUAL_TIMEOUT: "数値が届かないまま打ち切り",
    ScreenedCandidateStage.ENRICHMENT_CAP: "順位が下位で詳細を取得せず",
    ScreenedCandidateStage.GATE_REJECT: "入口ゲートで落選",
    ScreenedCandidateStage.RANKING_CUTOFF: "入口ゲート通過",
}
# The five things that can earn ranking points, in the words the user used
# when asking for the breakdown.
_BREAKDOWN_JA = (
    ("eps", "EPSサプライズ"),
    ("revenue", "売上サプライズ"),
    ("gap", "決算当日の値動き"),
    ("guidance", "会社のガイダンス"),
    ("whisper", "囁き予想の上回り"),
)

_CSV_COLUMNS: tuple[tuple[str, str], ...] = (
    ("ティッカー", "ticker"),
    ("発表日", "event_date"),
    ("順位", "rank"),
    ("到達段階", "stage"),
    ("数値の出所", "numbers_source"),
    # The same two cells the screen shows, with the display abbreviation
    # removed — full figures, so a spreadsheet can still divide them (T-014).
    ("EPS 実績/予想", "eps_pair"),
    ("EPSサプライズ率", "eps_surprise_pct"),
    ("売上 実績/予想", "revenue_pair"),
    ("売上サプライズ率", "revenue_surprise_pct"),
    ("ガイダンス", "guidance_state"),
    # What the guidance score was computed FROM (T-018). The column above says
    # only whether an outlook was obtained; these say what the company
    # actually guided and what it was measured against, so the guidance term
    # of the score can be divided out by hand like every other term can.
    # Multi-valued down the row rather than across it: one release routinely
    # guides the next quarter AND the full year (T-020), and the three cells
    # of a unit stay aligned entry for entry.
    ("EPSガイダンス 対象期", "eps_guidance_period"),
    ("EPSガイダンス 会社見通し", "eps_guidance_company"),
    ("EPSガイダンス コンセンサス", "eps_guidance_consensus"),
    ("売上ガイダンス 対象期", "revenue_guidance_period"),
    ("売上ガイダンス 会社見通し", "revenue_guidance_company"),
    ("売上ガイダンス コンセンサス", "revenue_guidance_consensus"),
    ("エラー", "errors"),
    ("点数", "score"),
    ("EPSで得た点", "eps"),
    ("売上で得た点", "revenue"),
    ("決算当日の値動きで得た点", "gap"),
    ("ガイダンスで得た点", "guidance"),
    ("囁き予想で得た点", "whisper"),
    ("株価", "price"),
    ("落選理由", "drop_reason"),
    ("取得できなかった理由", "numbers_reason"),
    ("見通しが読めなかった理由", "guidance_reason"),
    # How the company's own release was cut (T-013). On every row rather than
    # only the ranked ones: "which names do we keep failing to read, and is
    # the fault ours or the extractor's" is a question about the whole scan.
    ("発表文 採用ブロック数", "cause_blocks_kept"),
    ("発表文 変換ミスを修正した数", "cause_blocks_repaired"),
    ("発表文 抜き出し役が改変した数", "cause_blocks_altered"),
    ("発表文 却下した数", "cause_blocks_refused"),
)


def render_scan_report_ja(scan: dict, candidates: list[ScreenedCandidate],
                          top_n: int = 3) -> str:
    """One scan, as the user reads it before saying whether to proceed."""
    ranked, others = _split(candidates, top_n)
    lines = _header(scan, candidates)
    lines += _tribunal_section(scan, ranked, top_n)
    lines += _material_section(ranked)
    lines += _table_section(ranked + others)
    lines += _errors_section(candidates)
    lines += _release_reading_section(candidates)
    return "\n".join(lines)


# --- ⑤ how the companies' own releases were cut (T-013) ---------------------

def _release_reading_section(candidates: list[ScreenedCandidate]) -> list[str]:
    """The whole scan's tally, printed at zero as well.

    Section ② carries this per name, but only for the names going to the
    tribunal — and on a day when nothing clears the entry gates that section
    is empty, which is exactly a day when a defect on our side could run
    unnoticed. The T-012 case was found only because someone measured the
    refusal rate by hand; this section is that measurement, taken every run.

    The two middle numbers are the ones worth reading. A repair is almost
    always OUR text conversion having broken the release, and an alteration
    is the extractor having changed a letter or digit of the company's own
    sentence. Neither shows up anywhere else, because the excerpt the
    tribunal reads is cut from the release and is correct either way.
    """
    read = [c for c in candidates
            if (c.cause_blocks_kept + c.cause_blocks_repaired
                + c.cause_blocks_altered + c.cause_blocks_refused)]
    kept = sum(c.cause_blocks_kept for c in read)
    repaired = sum(c.cause_blocks_repaired for c in read)
    altered = sum(c.cause_blocks_altered for c in read)
    refused = sum(c.cause_blocks_refused for c in read)
    lines = ["## ⑤ 決算発表文の読み取り", ""]
    if not read:
        lines += ["この回は、会社の決算発表文を1銘柄も読んでいません"
                  "(抜き出し役が使えなかったか、詳細取得まで進んだ銘柄が"
                  "ありませんでした)。", ""]
        return lines
    lines += [f"{len(read)}銘柄の決算発表文から、審理に渡す抜粋を作りました。"
              f"抜粋に入った文の数は **{kept + repaired + altered}件** です。",
              "",
              f"- そのまま採用: **{kept}件**",
              f"- こちらの文章変換のミスを直して採用: **{repaired}件**",
              f"- 抜き出し役が会社の語句を改変していたので原文の文字に"
              f"置き換えて採用: **{altered}件**",
              f"- 発表文のどこにも近い箇所が無く却下: **{refused}件**",
              ""]
    if repaired:
        names = "、".join(c.ticker for c in read if c.cause_blocks_repaired)
        lines += [f"⚠️ **こちら側の不具合の疑い**: {names} で、発表文を"
                  "文章に直す処理が原文を壊していた可能性があります。"
                  "抜粋の中身は原文の文字なので正しいですが、"
                  "`hawkeye cause source ティッカー` で確認してください。", ""]
    if altered:
        names = "、".join(c.ticker for c in read if c.cause_blocks_altered)
        lines += [f"⚠️ **抜き出し役による改変**: {names} で、抜き出し役が"
                  "会社の文の英数字を書き換えていました。審理に渡すのは"
                  "発表文の文字に置き換えたものなので中身は正しいですが、"
                  "何を書き換えたかは "
                  "`hawkeye cause source ティッカー` で見られます。", ""]
    return lines


# --- header -----------------------------------------------------------------

def _header(scan: dict, candidates: list[ScreenedCandidate]) -> list[str]:
    params = scan.get("params") or {}
    start, end = params.get("window_start", "?"), params.get("window_end", "?")
    return [
        f"# 📄 走査レポート({start} 〜 {end})",
        "",
        f"走査番号 {scan.get('id', '?')} / 実行 {scan.get('ts', '?')} / "
        f"記録された銘柄 {len(candidates)}件",
        "",
        f"決算イベント {scan.get('scanned', 0)}件 → サプライズ選別 "
        f"{scan.get('screened', 0)}件 → 詳細取得 {scan.get('enriched', 0)}件 "
        f"→ 入口ゲート通過 {scan.get('gate_passed', 0)}件",
        "",
        "この回の走査が**何を見て、何を審理に送り、他を何故落としたか**の報告です。"
        "審理(強気役・反論役・裁定役による対審)はまだ始まっていません。",
        "",
    ]


# --- ① the names going to the tribunal --------------------------------------

def _tribunal_section(scan: dict, ranked: list[ScreenedCandidate],
                      top_n: int) -> list[str]:
    lines = [f"## ① 審理に送る{top_n}銘柄", ""]
    lines += _missing_ranked_note(scan, ranked, top_n)
    if not ranked:
        if not scan.get("gate_passed"):
            lines += ["審理に送れる銘柄は **0件** でした"
                      "(入口ゲートを通過した銘柄がありません)。", ""]
        return lines
    for c in ranked:
        lines.append(f"### {c.rank or '-'}位 {c.ticker} — 点数 {c.score:g}")
        lines.append("")
        lines += _breakdown_lines(c)
        lines.append("")
        lines += _gate_lines(c.gate_report)
        lines.append("")
    return lines


def _missing_ranked_note(scan: dict, ranked: list[ScreenedCandidate],
                         top_n: int) -> list[str]:
    """Names the scan ranked but this report cannot describe.

    The ledger's drop table records what a run did NOT forward. A run started
    with `--open-cases N` forwards its top N in the same breath, so those rows
    are never written — and this report, built from that table, would print
    the fourth-placed name as if it were the first. The report has to say the
    detail is missing; silently showing a shorter list is the failure mode
    this whole document exists to prevent.
    """
    gate_passed = scan.get("gate_passed") or 0
    expected = min(top_n, gate_passed)
    if len(ranked) >= expected:
        return []
    named = [t for t in (scan.get("tickers") or [])[:expected]
             if t not in {c.ticker for c in ranked}]
    return [f"⚠️ **上位 {expected}銘柄のうち {expected - len(ranked)}件"
            f"({'、'.join(named) or '銘柄名も不明'})の詳細がここにありません。**"
            "この走査は候補を審理に直接送る指定"
            "(`--open-cases`)付きで実行されたため、送られた銘柄は"
            "「落選記録」に残らず、このレポートの材料が存在しません。"
            "`/hawkeye-run` の手順どおり `--open-cases` を付けずに走査すれば"
            "全件そろいます。",
            ""]


def _breakdown_lines(c: ScreenedCandidate) -> list[str]:
    """What earned the score, or an honest statement that nothing recorded it.

    Five zeros would read as "nothing earned any points", which is a claim
    about the company. "Not recorded" is a claim about us, and it is the true
    one for any row written before this field existed.
    """
    if c.score_breakdown is None:
        return ["**点数の内訳は記録されていません**"
                "(この行は内訳を記録するようになる前の走査のものです)。"]
        # 内訳が無くても点数そのものは上の見出しに出ている。
    b = c.score_breakdown
    parts = "  ".join(f"{label} {getattr(b, attr):+g}"
                      for attr, label in _BREAKDOWN_JA)
    lines = [f"点数の内訳: {parts}"]
    lines += ["",
              "(ニュース・インサイダー売買・アナリスト推奨は**点数には使って"
              "いません**。審理に渡す資料です)"]
    return lines


def _gate_lines(report: Optional[GateReport]) -> list[str]:
    if report is None:
        return ["入口ゲートの判定は記録されていません。"]
    lines = ["入口ゲート7条件:"]
    for g in report.results:
        if g.unverified:
            mark, tail = "⚠️", " — 判定に必要な数値が取れませんでした"
        elif g.passed:
            mark, tail = "✅", ""
        else:
            mark = "❌" if g.hard else "⚠️"
            tail = " — 不合格" if g.hard else " — 注意(致命的ではない)"
        # The measured figure is printed even when the condition has no
        # numeric bar (`earnings_proximity` passes on any date far enough
        # out). Without this branch that line read as a bare ✅ with nothing
        # behind it — a condition the reader is told cleared, on evidence they
        # were not shown (found on the first live run).
        if g.value is not None and g.threshold is not None:
            value = f" (実測 {g.value:,.2f} / 基準 {g.threshold:,.2f})"
        elif g.value is not None:
            value = f" (実測 {g.value:,.2f})"
        else:
            value = ""
        lines.append(f"- {mark} {_GATE_JA.get(g.name, g.name)}{value}{tail}")
    return lines


# --- ② everything that was NOT the earnings figures -------------------------

def _material_section(ranked: list[ScreenedCandidate]) -> list[str]:
    lines = ["## ② 決算値以外に、審理へ渡す情報", "",
             "⚠️ **これらは点数には使っていません。** 点数はEPS・売上・"
             "会社のガイダンス・囁き予想・決算当日の値動きの5つだけで決まります。"
             "ここに挙げるのは、審理で強気役と反論役が材料として読むものです。",
             ""]
    if not ranked:
        lines += ["該当なし。", ""]
        return lines
    for c in ranked:
        lines.append(f"### {c.ticker}")
        lines += _news_lines(c.news)
        lines.append(_insider_line(c.insider_activity))
        lines.append(_analyst_line(c.analyst_trend))
        lines.append(_cause_source_line(c))
        lines.append("")
    return lines


def _cause_source_line(c: ScreenedCandidate) -> str:
    """How the company's own release was cut into the excerpt (T-013).

    Printed for every ranked name including the all-zero case, because the
    two numbers this line exists for only mean something when they are always
    there. "修正" is our own text conversion having broken the release (the
    T-012 defect, 13 real explanations lost before it was found); "改変" is
    the extractor having changed a letter or a digit of the company's own
    sentence. The excerpt is correct either way — the release's characters
    are what get cut — so if this line were omitted when it read zero, a run
    where the extractor rewrote a figure would look identical to a clean one.
    """
    read = (c.cause_blocks_kept + c.cause_blocks_repaired
            + c.cause_blocks_altered + c.cause_blocks_refused)
    if not read:
        return ("- 決算発表文からの抜粋: この銘柄では読んでいません"
                "(順位が下位で詳細を取得しなかったか、抜き出し役が"
                "使えませんでした)")
    line = (f"- 決算発表文からの抜粋: 採用 {c.cause_blocks_kept}件 / "
            f"こちらの変換ミスを修正して採用 {c.cause_blocks_repaired}件 / "
            f"抜き出し役が語句を改変 {c.cause_blocks_altered}件 / "
            f"原文に無く却下 {c.cause_blocks_refused}件")
    if c.cause_blocks_altered:
        line += ("\n  - ⚠️ **改変あり**: 抜き出し役が会社の文の英数字を"
                 "書き換えました。審理に渡す抜粋は発表文の文字で置き換えて"
                 "あるので中身は正しいですが、`hawkeye cause source "
                 f"{c.ticker}` で何が書き換えられたか確認できます。")
    return line


def _news_lines(news: list[NewsItem]) -> list[str]:
    if not news:
        return ["- ニュース: 取得できたものはありません"]
    out = []
    for item in news:
        day = (item.published_at.date().isoformat()
               if item.published_at else "日付不明")
        source = f"({item.source})" if item.source else ""
        out.append(f"- ニュース {day}: 「{item.headline}」{source}")
    return out


def _insider_line(activity: Optional[InsiderActivity]) -> str:
    if activity is None:
        return "- インサイダー売買: 記録なし(取得できなかったか、届出が無い)"
    direction = "買い越し" if activity.net_shares > 0 else "売り越し"
    return (f"- インサイダー売買: 直近{activity.window_days}日で "
            f"{abs(activity.net_shares):,.0f}株の{direction}"
            f"(買った人 {activity.buyers}人 / 売った人 {activity.sellers}人)")


def _analyst_line(trend: Optional[AnalystTrend]) -> str:
    if trend is None:
        return "- アナリスト推奨: 記録なし"
    now = (f"強気買い {trend.strong_buy} / 買い {trend.buy} / "
           f"中立 {trend.hold} / 売り {trend.sell} / "
           f"強気売り {trend.strong_sell}")
    if trend.prior_period is None:
        return f"- アナリスト推奨({trend.period}時点): {now}"
    before = (f"強気買い {trend.prior_strong_buy} / 買い {trend.prior_buy} / "
              f"中立 {trend.prior_hold} / 売り {trend.prior_sell} / "
              f"強気売り {trend.prior_strong_sell}")
    return (f"- アナリスト推奨: {trend.prior_period}時点は {before} → "
            f"{trend.period}時点は {now}")


# --- ③ every name the scan recorded -----------------------------------------

def _looked_at_closely(c: ScreenedCandidate) -> bool:
    """Whether anything beyond the calendar's own figures happened to a name.

    True when the earnings feed was asked about it (it answered, or it
    declined by name), or when the walk reached it at all — enrichment, the
    entry gates, or a hold waiting for its numbers.

    Everything else cleared the surprise screen and then sat below the
    request budget, so its row would read: calendar figures, calendar source,
    and the same one-sentence reason as every other such row. On the first
    live run that was 121 of 171 rows, and it buried the fifty that record an
    actual retrieval decision — the same failure the check sheet hit on
    2026-08-10.
    """
    return (c.numbers_source == "whispers" or bool(c.numbers_reason)
            or c.gate_report is not None
            or c.stage in (ScreenedCandidateStage.GATE_REJECT,
                           ScreenedCandidateStage.ACTUAL_PENDING,
                           ScreenedCandidateStage.ACTUAL_TIMEOUT))


def _reading_order(c: ScreenedCandidate) -> tuple[int, int, float]:
    """Rank first and in rank order, then everything else by score (T-014).

    The ledger's own order is the order the scan dropped names in, which put
    50 above 5.76 above 0 above 60 above 85 on the first live run — a column
    of numbers in no order at all. A reader scanning for "what nearly made
    it" has to be able to read down.
    """
    if c.rank is not None:
        return (0, c.rank, 0.0)
    return (1, 0, -c.score)


def _table_section(rows: list[ScreenedCandidate]) -> list[str]:
    shown = sorted((c for c in rows if _looked_at_closely(c)),
                   key=_reading_order)
    hidden = len(rows) - len(shown)
    lines = [f"## ③ 走査した銘柄({len(shown)}件)", ""]
    if not shown:
        lines += [f"表に出せる銘柄は **0件** です"
                  f"(この回に記録された銘柄は {len(rows)}件)。", ""]
        return lines
    lines += ["決算専門サイト(EW)に数字を問い合わせた銘柄と、入口ゲートまで"
              "進んだ銘柄の全件です。順位の付いた銘柄が上、付かなかった銘柄が"
              "その下(点数の高い順)に並びます。「落選理由」はどの段階で外れたか、"
              "「エラー」はこの銘柄で何の取得・読み取りが失敗したかを示し、"
              "その中身は次の④に書いてあります。",
              "",
              "| ティッカー | 発表日 | 順位 | EPS 実績/予想 | EPSサプライズ "
              "| 売上 実績/予想 | 売上サプライズ | ガイダンス | 数値の出所 "
              "| エラー | 点数 | 落選理由 |",
              "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- "
              "| --- | --- |"]
    for c in shown:
        lines.append(
            f"| {c.ticker} | {c.event_date} | {c.rank or '-'} "
            f"| {_eps_pair(c)} | {_pct(c.eps_surprise_pct)} "
            f"| {_revenue_pair(c)} | {_pct(c.revenue_surprise_pct)} "
            f"| {_GUIDANCE_STATE_JA.get(c.guidance_state, '記録なし')} "
            f"| {_SOURCE_JA.get(c.numbers_source, c.numbers_source)} "
            f"| {_errors_cell(c)} "
            f"| {c.score:g} | {_drop_reason_ja(c)} |")
    lines.append("")
    if hidden:
        lines += [f"ほかに **{hidden}件** が、サプライズの足切りは通ったものの"
                  f"順位が下位で、決算専門サイトへの問い合わせにも詳細取得にも"
                  f"進みませんでした(上限は設定値 `scout_max_whispers` / "
                  f"`scout_max_enrich`)。数値は決算カレンダーのもの1種類しか"
                  f"無く、落選理由も全件同じなので表からは省いています — "
                  f"**CSVには全{len(rows)}件が入っています**。", ""]
    return lines


def _drop_reason_ja(c: ScreenedCandidate) -> str:
    """Why this name is not in the tribunal, in words that name the condition.

    The stored `reject_reason` is an English identifier written for a later
    machine review. Rebuilding the sentence from the gate report instead means
    the user reads WHICH condition refused the company, which is the only form
    of the answer they can disagree with.
    """
    if c.stage is ScreenedCandidateStage.GATE_REJECT:
        if c.gate_report is None:
            return "入口ゲートで落選(判定の記録なし)"
        failed = [_GATE_JA.get(g.name, g.name)
                  for g in c.gate_report.results
                  if g.hard and (not g.passed or g.unverified)]
        if failed:
            return "入口ゲート不合格: " + " / ".join(failed)
        return "入口ゲートで落選(致命的な不合格は記録されていません)"
    if c.stage is ScreenedCandidateStage.RANKING_CUTOFF:
        return (f"入口ゲート通過(順位 {c.rank}位)" if c.rank
                else _STAGE_JA[c.stage])
    return _STAGE_JA.get(c.stage, str(c.stage))


# --- ④ what could not be retrieved ------------------------------------------

def _errors_section(candidates: list[ScreenedCandidate]) -> list[str]:
    """Every failure the table's エラー column flags, said in words (T-014).

    Three kinds, each with its own subsection, because the reader's next move
    differs: the earnings feed declining to supply figures is a vendor gap the
    ranking already worked around, an unreadable outlook is usually a defect
    on our side, and a refused or altered release block changes what the
    tribunal is handed. One list would flatten all three into "some things
    failed".

    Printed at zero as well: a section that vanishes when nothing failed reads
    as a check nobody ran, and this is the one place a silent data outage
    would otherwise be invisible to the user.
    """
    numbers = [c for c in candidates if c.numbers_reason]
    conflicts = [c for c in candidates if c.conflicting_estimates]
    guidance = [c for c in candidates
                if c.guidance_state is GuidanceState.UNREADABLE]
    release = [c for c in candidates
               if c.cause_blocks_refused or c.cause_blocks_altered]
    affected = {c.ticker for c in numbers + conflicts + guidance + release}
    lines = [f"## ④ 取得・読み取りに失敗したもの({len(affected)}銘柄)", ""]
    if not affected:
        lines += ["**0件** — この回はどの銘柄でも、決算数値・会社の見通し・"
                  "決算発表文のいずれの取得・読み取りにも失敗していません。", ""]
        return lines
    lines += _numbers_failures(numbers, conflicts)
    lines += _guidance_failures(guidance)
    lines += _release_failures(release)
    return lines


def _by_reason(candidates: list[ScreenedCandidate], attr: str) -> list[str]:
    """Reason-first, tickers after — never one paragraph per ticker.

    The reason sentences are long, and thirteen repetitions of three sentences
    hide which reason is the common one. The grouping is what says "the site
    was down" rather than "these thirteen companies are odd".
    """
    grouped: dict[str, list[str]] = {}
    for c in candidates:
        grouped.setdefault(getattr(c, attr), []).append(c.ticker)
    return [f"- {_flag_ja(reason)} — **{len(tickers)}件**: "
            f"{'、'.join(tickers)}"
            for reason, tickers in grouped.items()]


def _numbers_failures(numbers: list[ScreenedCandidate],
                      conflicts: list[ScreenedCandidate]) -> list[str]:
    if not numbers and not conflicts:
        return []
    lines = ["### 決算数値(EPS・売上)", ""]
    if numbers:
        lines += ["決算専門サイト(EW)が数字を出せなかった銘柄です。"
                  "いずれも決算カレンダー(Finnhub)の数字で順位を付けています。",
                  ""]
        lines += _by_reason(numbers, "numbers_reason")
    for c in conflicts:
        lines.append(f"- **{c.ticker}**: 決算カレンダー(Finnhub)が同じ決算に"
                     f"矛盾する行を返しました"
                     f"(最も保守的な読みを採用しています)")
    lines.append("")
    return lines


def _guidance_failures(guidance: list[ScreenedCandidate]) -> list[str]:
    """Only the readings that FAILED — never the companies that guided nothing.

    Most companies publish no outlook and that costs them no points; listing
    them here would bury the handful where we asked, the company had spoken,
    and we came away with nothing.
    """
    if not guidance:
        return []
    return (["### 会社の見通し(ガイダンス)", "",
             "会社が来期の見通しに触れているのに読み取れなかった、または"
             "読み取り自体が終わっていない銘柄です。**会社が何も言っていない"
             "という意味ではありません** — 点数のガイダンス欄は0点になって"
             "いますが、それはこちら側が読めていないためです。", ""]
            + _by_reason(guidance, "guidance_reason") + [""])


def _release_failures(release: list[ScreenedCandidate]) -> list[str]:
    """Blocks that never reached the excerpt, and words the extractor changed.

    Both are stated per ticker rather than grouped: there is no shared reason
    to group by — what happened is a count, and the count is the finding.
    """
    if not release:
        return []
    lines = ["### 決算発表文からの抜粋", "",
             "会社自身がその決算を説明した文から抜粋を作る工程で、審理3役に"
             "渡らなかった、または書き換えられていた箇所がある銘柄です。"
             "抜粋に載るのは常に発表文そのものの文字なので中身は正しいですが、"
             "却下された分だけ3役の材料は薄くなっています。", ""]
    for c in release:
        parts = []
        if c.cause_blocks_refused:
            parts.append(f"発表文のどこにも近い箇所が無く却下 "
                         f"{c.cause_blocks_refused}件")
        if c.cause_blocks_altered:
            parts.append(f"抜き出し役が会社の語句を改変(原文の文字に置換して"
                         f"採用) {c.cause_blocks_altered}件")
        lines.append(f"- **{c.ticker}**: {' / '.join(parts)} — "
                     f"`hawkeye cause source {c.ticker}` で中身を確認できます")
    lines.append("")
    return lines


# --- the same rows, for a spreadsheet ---------------------------------------

def scan_report_csv(candidates: Iterable[ScreenedCandidate]) -> str:
    """One line per candidate, translated exactly as the screen translates it.

    The file and the screen are read by the same person, so a spreadsheet full
    of `gate_reject` and `whispers_server_error` is not a second surface — it
    is the same surface with the translation removed.
    """
    buffer = io.StringIO()
    writer = csv.writer(buffer, lineterminator="\n")
    writer.writerow([header for header, _ in _CSV_COLUMNS])
    for c in candidates:
        writer.writerow([_csv_cell(attr, c) for _, attr in _CSV_COLUMNS])
    return buffer.getvalue()


def _csv_cell(attr: str, c: ScreenedCandidate) -> str:
    if attr == "stage":
        return _STAGE_JA.get(c.stage, str(c.stage))
    if attr == "numbers_source":
        return _SOURCE_JA.get(c.numbers_source, c.numbers_source)
    if attr == "numbers_reason":
        return _flag_ja(c.numbers_reason) if c.numbers_reason else ""
    if attr == "guidance_reason":
        return _flag_ja(c.guidance_reason) if c.guidance_reason else ""
    if attr == "guidance_state":
        return _GUIDANCE_STATE_JA.get(c.guidance_state, "記録なし")
    if attr == "errors":
        # The file gets sentences where the screen gets one word. The screen
        # has §④ under it to say what the word meant; a spreadsheet opened a
        # week later has nothing, and "数値" told nobody anything (T-018).
        return "".join(_failure_sentences(c))
    if attr.endswith("_guidance_period"):
        return _guidance_cells(c, attr[:-len("_guidance_period")])[0]
    if attr.endswith("_guidance_company"):
        return _guidance_cells(c, attr[:-len("_guidance_company")])[1]
    if attr.endswith("_guidance_consensus"):
        return _guidance_cells(c, attr[:-len("_guidance_consensus")])[2]
    # The screen's two combined cells, with the abbreviation removed: the file
    # is the same surface without the translation, so the figures arrive whole
    # and a spreadsheet can still divide one by the other.
    if attr == "eps_pair":
        return f"{_plain(c.eps_actual)} / {_plain(c.eps_estimate)}"
    if attr == "revenue_pair":
        return f"{_plain(c.revenue_actual)} / {_plain(c.revenue_estimate)}"
    if attr == "drop_reason":
        return _drop_reason_ja(c)
    if attr in ("eps_surprise_pct", "revenue_surprise_pct"):
        value = getattr(c, attr)
        return "" if value is None else f"{round(value, 2):g}"
    if attr in ("eps", "revenue", "gap", "guidance", "whisper"):
        if c.score_breakdown is None:
            return ""
        return f"{getattr(c.score_breakdown, attr):g}"
    value = getattr(c, attr, None)
    return "" if value is None else str(value)


def _pct(value: Optional[float]) -> str:
    return "-" if value is None else f"{value:+.1f}%"


# --- the figures behind the percentages (T-014) ------------------------------

def _eps(value: Optional[float]) -> str:
    """An EPS figure as the vendor stated it. `-` is "not obtained", never 0."""
    return "-" if value is None else f"{value:g}"


def _plain(value: Optional[float]) -> str:
    """A figure written out in full, for the spreadsheet.

    `:g` turns revenue into 1.33462e+08, which a spreadsheet reads as text and
    a person reads as nothing.
    """
    if value is None:
        return "-"
    return f"{value:f}".rstrip("0").rstrip(".") or "0"


def _money(value: Optional[float]) -> str:
    """A revenue figure, abbreviated so the column stays readable.

    Revenue arrives in dollars — 133462000 — and a table of nine-digit numbers
    beside three-digit percentages is a table nobody reads across. The CSV
    keeps the full figures.
    """
    if value is None:
        return "-"
    size = abs(value)
    if size >= 1e9:
        return f"{value / 1e9:.2f}B"
    if size >= 1e6:
        return f"{value / 1e6:.1f}M"
    if size >= 1e3:
        return f"{value / 1e3:.1f}K"
    return f"{value:,.0f}"


def _eps_pair(c: ScreenedCandidate) -> str:
    return f"{_eps(c.eps_actual)} / {_eps(c.eps_estimate)}"


def _revenue_pair(c: ScreenedCandidate) -> str:
    return f"{_money(c.revenue_actual)} / {_money(c.revenue_estimate)}"


# --- what failed, per name (T-014) ------------------------------------------
#
# Three kinds, and they are three separate mechanisms rather than three
# severities of one: the earnings feed declining to supply figures, the
# company's outlook not being readable, and the release excerpt losing blocks.
# The table names which one fired; §④ says what it actually was.

_ERROR_NUMBERS = "数値"
_ERROR_GUIDANCE = "見通し"
_ERROR_RELEASE = "発表文"


def _failure_kinds(c: ScreenedCandidate) -> list[str]:
    kinds = []
    if c.numbers_reason:
        kinds.append(_ERROR_NUMBERS)
    if c.guidance_state is GuidanceState.UNREADABLE:
        kinds.append(_ERROR_GUIDANCE)
    # A repaired block is not listed here: it was OUR text conversion, it was
    # repaired, and the excerpt carries the release's own characters — §⑤
    # already reports it as the defect on our side that it is. Refused and
    # altered are the two that changed what the tribunal receives.
    if c.cause_blocks_refused or c.cause_blocks_altered:
        kinds.append(_ERROR_RELEASE)
    return kinds


def _errors_cell(c: ScreenedCandidate) -> str:
    return "・".join(_failure_kinds(c)) or "-"


# The same three mechanisms, written out for the file. One sentence each,
# ending in a full stop, so that two of them concatenate into two readable
# sentences without a separator — a separator would leave the first sentence
# ending in "しました／", which reads as a fragment.
_FAILURE_SENTENCE = {
    _ERROR_NUMBERS: "決算専門サイトからEPSまたは売上の数値が取れず、"
                    "決算カレンダーの数字で判定しました。",
    _ERROR_GUIDANCE: "会社は見通しを述べているのに、こちらが読み取れません"
                     "でした。",
    _ERROR_RELEASE: "審理に渡す決算発表文の抜粋の一部が、却下されたか"
                    "語句を改変されていました。",
}


def _failure_sentences(c: ScreenedCandidate) -> list[str]:
    return [_FAILURE_SENTENCE[kind] for kind in _failure_kinds(c)]


# --- what the company guided, and what it was measured against (T-018) ------

_PERIOD_KIND_JA = {"next_quarter": "翌四半期", "full_year": "通期",
                   # The company guided a period neither yardstick covers, so
                   # nothing was compared. Saying so in the cell keeps the
                   # blank consensus beside it from reading as a data gap.
                   "other": "比較対象外"}


def _period_ja(g: GuidanceComparison) -> str:
    """`2026-Q3（翌四半期）` — the company's own label, and what it means.

    The label alone does not say whether that quarter is the one AHEAD of the
    print, and the record downstream keeps no fiscal quarter to work it out
    from, so both halves go in the one cell (User decision, 2026-08-19).
    """
    kind = _PERIOD_KIND_JA.get(g.period_kind, "")
    if not g.period:
        return kind or "-"
    return f"{g.period}（{kind}）" if kind else g.period


def _guidance_cells(c: ScreenedCandidate, unit: str) -> tuple[str, str, str]:
    """(periods, what the company guided, the bar) for one unit, aligned.

    All three are empty when the company guided nothing for this unit — NOT
    `-`. A blank cell and a cell reading `-` would otherwise both appear, and
    the reader would have to guess which meant "guided nothing at all"; the
    ガイダンス column beside them already answers that in words.

    A range is entered as its midpoint alone (User decision, 2026-08-19): it
    is the figure the comparison used and the one a spreadsheet can divide.
    The ends are not lost — they stay on the print row in the ledger.
    """
    rows = [g for g in c.guidance_comparisons if g.unit == unit]
    if not rows:
        return "", "", ""
    return ("、".join(_period_ja(g) for g in rows),
            "、".join(_plain(g.company) for g in rows),
            "、".join(_plain(g.consensus) for g in rows))


def _split(candidates: list[ScreenedCandidate], top_n: int
           ) -> tuple[list[ScreenedCandidate], list[ScreenedCandidate]]:
    """(the names going to the tribunal, everything else).

    Ranked names come first and in rank order; the rest keep the ledger's own
    order, which is the order the scan dropped them in.
    """
    ranked = sorted((c for c in candidates
                     if c.rank is not None and c.rank <= top_n),
                    key=lambda c: c.rank or 0)
    chosen = {c.id for c in ranked}
    return ranked, [c for c in candidates if c.id not in chosen]
